version: "3.8"
services:
  apis:
    build: .
    depends_on:
      - postgres

    ports:
      - 8000:9000
    volumes:
    #mount_bind
      - ./:/usr/scr/app:ro
    command: uvicorn App.main:app --host 0.0.0.0 --port 9000 --reload
    # environment:
    #    DATABASE_HOSTNAME: postgres
    env_file:
      - ".env"
  # - ./.env

  postgres:

    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: fastapi
    ports:
        - 5678:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: {}
